NTB.Odds.Input/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using NTB.Odds.Input.DataMappers.UserProfiles;
using NTB.Odds.Input.Domain.Classes;

namespace NTB.Odds.Input.Controllers
{
    public class ProfileController : Controller
    {
        //
        // GET: /Profile/

        public ActionResult Index()
        {
            var userProfileDataMapper = new UserProfileDataMapper();
            var user = new Guid(Membership.GetUser().ProviderUserKey.ToString());
            var userProfile = userProfileDataMapper.GetUserProfile(user);
            return View(userProfile);
            
        }

        //
        // GET: /Profile/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Profile/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Profile/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        public ActionResult Edit(string id)
        {
            var userProfileDataMapper = new UserProfileDataMapper();
            var user = new Guid(id);
            var userProfile = userProfileDataMapper.GetUserProfile(user);
            return View(userProfile);
        }
        
        //
        // GET: /Profile/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //
        // POST: /Profile/Edit/5

        [HttpPost]
        public ActionResult Edit(string id, FormCollection collection)
        {
            try
            {
                // Get the UserId from the URL
                var foo = new Guid(id);
                var user = new Guid(Membership.GetUser().ProviderUserKey.ToString());                
                var userProfile = new UserProfile
                    {
                        FirstName = collection["firstname"],
                        LastName = collection["lastname"],
                        Signature = collection["signature"],
                        UserId = user
                    };

                var userProfileDataMapper = new UserProfileDataMapper();

                var u = userProfileDataMapper.GetUserProfile(user);
                if (u.FirstName == null)
                {
                    userProfileDataMapper.InsertProfile(userProfile);
                }
                else
                {
                    userProfileDataMapper.Update(userProfile);
                }
                

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Profile/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Profile/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NTB.Odds.Input/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/ui-lightness/jquery-ui.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.8.2.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/ui/jquery-ui.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script> 
    </head>
    <body>
        <div class="container-fluid">
            <div id="header" class="row-fluid">
                <div id="mymenucontainer" class="row-fluid">
                    <div class="navbar navbar-default">
                        <div class="container">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="#">NTB Odds Input</a>
                            </div>
                            <div class="collapse navbar-collapse">
                                <ul class="nav navbar-nav">
                                    <li class="@(ViewBag.Active == "Home" ? "active" : "")">
                                        @Html.ActionLink("Home", "Index", "Home")
                                    </li>
                                    <li class="@(ViewBag.Active == "About" ? "active" : "")">
                                        @Html.ActionLink("About", "About", "Home")
                                    </li>
                                    @Html.Partial("_LogOnPartial")
                                </ul>
                            </div><!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
            </div>
            <div id="row-fluid">
                @RenderBody()
            </div>
            <div id="row-fluid">
            </div>
        </div>
        
        
        <script type="text/javascript">
            $(document).ready(function () {
                $("#datepicker").datepicker({
                    dateFormat:'dd-mm-yy'
                });
                $("input[type=submit]").click(function () {

                    var formId = this.form.id;

                    if (formId == null) {
                        return true;
                    }

                    var matchId = formId.replace("registermatch_", "");
                    if (matchId != "") {
                        var vurdering = $("#vurdering_" + matchId);
                        var odds = $("#matchodds_" + matchId);
                        var buttonSave = $("#btn_" + matchId);

                        $.ajax({
                            type: 'POST',
                            url: '/Article/PostComment/' + matchId,
                            data: $("#" + formId + ' :input').serialize(),
                            success: function (returndata) {
                                $("#btn_" + matchId).attr("value", "Oppdater");
                            },
                            error: function () {
                                alert("Error!");
                            }
                        });

                        return false;
                    }
                });

            });
        </script>
    </body>
</html>

NTB.Odds.Input/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <li class="@(ViewBag.Active == "Home" ? "active" : "")">
        @Html.ActionLink("Import", "Index", "Import")
    </li>
    
    if (Convert.ToBoolean(Session["ImportedMatches"]))
    {
    <li class="@(ViewBag.Active == "Article" ? "active" : "")">
        @Html.ActionLink("Vurderinger", "Index", "Article")
    </li>        
    
}

    <li id="userprofile" class="@(ViewBag.Active == "Home" ? "active" : "")">
        @Html.ActionLink("Profil", "Index", "Profile")
    </li>
    <li id="logindisplay" class="@(ViewBag.Active == "Home" ? "active" : "")">
        Welcome @User.Identity.Name
    </li>
    
    <li>@Html.ActionLink("Log Off", "LogOff", "Account")</li>
}
else
{
    
    <li id="logindisplay">@Html.ActionLink("Log On", "LogOn", "Account")</li>
}